% main_social_gating_simulation.m
% Minimal simulation for a social-gating model of helping behaviour.
%
% The model treats helping, prosocial choice, costly other-benefit action,
% strict altruism-like outcomes, empathy-like responding, and collaboration
% as outcome labels generated by one action-selection architecture.
%
% Version 5.3 changes:
%   - uses a default helping threshold that is reduced when direct actor benefit or weighted joint benefit is present;
%   - supports scalar or multi-seed runs;
%   - uses parameter-regime terminology rather than species terminology;
%   - outputs model-ablation scores rather than presenting them as fitted AIC;
%   - writes a compact manuscript-facing summary table;
%   - removes the fragile sg_getParameterRegimeParams dependency from main calls.
%
% Christoph D. Dahl / draft code generated for further development.

clear; clc;

rootDir = fileparts(fileparts(mfilename('fullpath')));
matlabDir = fileparts(mfilename('fullpath'));
addpath(genpath(matlabDir));
rehash;

outDir = fullfile(rootDir, 'results');
figDir = fullfile(rootDir, 'figures');
if ~exist(outDir, 'dir'), mkdir(outDir); end
if ~exist(figDir, 'dir'), mkdir(figDir); end

% Fail early if the local folder is incomplete or MATLAB is still using an old path.
requiredFunctions = {'sg_defaultParams','sg_taskPresets','sg_runSimulation', ...
    'sg_simulateTrial','sg_computeUtility', ...
    'sg_summariseResults','sg_counterfactualNeedEffect', ...
    'sg_logLikelihoodVariants','sg_plotResults_v2'};
for iReq = 1:numel(requiredFunctions)
    assert(exist(requiredFunctions{iReq}, 'file') == 2, ...
        'Required function not found on MATLAB path: %s. Check that you are running from the v5_3 /matlab folder.', ...
        requiredFunctions{iReq});
end

params = sg_defaultParams();
tasks  = sg_taskPresets();

% Parameter regimes, not species simulations.
% These labels describe settings of the same computational architecture.
parameterRegimes = {'modOther_highComp', ...      % moderate other-weight, high competition
                    'highOther_modComp', ...      % high other-weight, moderate competition
                    'highOther_lowComp', ...      % high other-weight, low competition
                    'lowOther_weight', ...        % low other-weight but residual social terms
                    'pureSelf'};                  % strict non-social valuation control

nTrialsPerTask = 500;

% Use a scalar seed for fast development. For manuscript robustness, use a
% vector, for example: seeds = 11:60;
seeds = 11;

data = sg_runSimulation(tasks, parameterRegimes, params, nTrialsPerTask, seeds);
summaryTbl = sg_summariseResults(data);
cfTbl = sg_counterfactualNeedEffect(tasks, parameterRegimes, params);
ablationTbl = sg_logLikelihoodVariants(data, parameterRegimes, params);

% Compact manuscript-facing summary.
compactVars = {'task','socialSystem','n','choiceHelpRate','helpingRate', ...
    'prosocialRate','costlyOtherBenefitRate','strictAltruismLikeRate', ...
    'collaborationLikeRate','falsePositiveRate','needFailureRate', ...
    'affordanceFailureRate','costCompetitionOverrideRate', ...
    'valuationNoHelpRate','falsePositiveBiasRate','successRate'};
summaryCompactTbl = summaryTbl(:, compactVars);

writetable(data, fullfile(outDir, 'trial_data.csv'));
writetable(summaryTbl, fullfile(outDir, 'summary_by_task_and_system.csv'));
writetable(summaryCompactTbl, fullfile(outDir, 'summary_for_manuscript.csv'));
writetable(cfTbl, fullfile(outDir, 'counterfactual_need_effect.csv'));
writetable(ablationTbl, fullfile(outDir, 'model_ablation_scores.csv'));

% Legacy output name retained for older manuscript scripts if needed.
writetable(ablationTbl, fullfile(outDir, 'nested_model_likelihoods.csv'));

plotCfg = sg_plotConfig();
sg_plotResults_v2(summaryTbl, data, cfTbl, ablationTbl, figDir, plotCfg);

disp('Social-gating simulation complete.');
disp(['Results written to: ' outDir]);
disp(['Figures written to: ' figDir]);

disp('Summary:');
disp(summaryTbl);
