function sg_applyPubStyle(ax, cfg)
%SG_APPLYPUBSTYLE Restrained grayscale manuscript axis style.

if nargin < 1 || isempty(ax)
    ax = gca;
end
if nargin < 2 || isempty(cfg)
    cfg = sg_pubFigureConfig();
end

set(ax, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'LineWidth', cfg.axisLineWidth, ...
    'FontName', cfg.fontName, ...
    'FontSize', cfg.fontSize, ...
    'XColor', [0 0 0], ...
    'YColor', [0 0 0], ...
    'Layer', 'top', ...
    'TickLabelInterpreter', 'none');

ax.TickLength = [0.015 0.015];
end
