function cfg = sg_plotConfig()
%SG_PLOTCONFIG Publication-oriented ordering and labels.

cfg.taskOrder = { ...
    'instrumental_reaching', ...
    'visible_tool_transfer', ...
    'hidden_tool_transfer', ...
    'food_token_randomised', ...
    'food_token_fixed_position', ...
    'apparatus_bias_no_benefit', ...
    'low_competition_provisioning', ...
    'high_cost_help', ...
    'dominance_risk_help', ...
    'reliable_partner_collaboration'};

cfg.taskLabels = { ...
    'Instrumental reaching', ...
    'Visible tool transfer', ...
    'Hidden tool transfer', ...
    'Food token, randomised', ...
    'Food token, fixed position', ...
    'Apparatus bias, no benefit', ...
    'Low-competition provisioning', ...
    'High-cost help', ...
    'Dominance-risk help', ...
    'Reliable-partner collaboration'};

cfg.systemOrder = { ...
    'modOther_highComp', ...
    'highOther_modComp', ...
    'highOther_lowComp', ...
    'lowOther_weight', ...
    'pureSelf'};

cfg.systemLabels = { ...
    'moderate other-weight / high competition', ...
    'high other-weight / moderate competition', ...
    'high other-weight / low competition', ...
    'low other-weight', ...
    'pure self-interest control'};


% Optional outcome labels for future plots/tables. These are not used in every
% figure, but keep manuscript-facing terminology consistent.
cfg.outcomeVars = { ...
    'choiceHelpRate', ...
    'helpingRate', ...
    'prosocialRate', ...
    'costlyOtherBenefitRate', ...
    'strictAltruismLikeRate', ...
    'collaborationLikeRate', ...
    'falsePositiveRate'};

cfg.outcomeLabels = { ...
    'help-like choice rate', ...
    'actual helping rate', ...
    'prosocial rate', ...
    'costly other-benefit rate', ...
    'strict altruism-like rate', ...
    'collaboration-like rate', ...
    'false-positive rate'};

cfg.failureVars = { ...
    'needFailureRate', ...
    'affordanceFailureRate', ...
    'costCompetitionOverrideRate', ...
    'valuationNoHelpRate', ...
    'falsePositiveBiasRate', ...
    'successRate'};

cfg.failureLabels = { ...
    'need-detection failure', ...
    'affordance failure', ...
    'cost/competition override', ...
    'valuation no-help', ...
    'false-positive bias', ...
    'success'};

% Muted manuscript colour palette.
% Rows correspond to parameter regimes.
cfg.regimeColors = [
    0.10 0.10 0.10   % near black
    0.23 0.37 0.55   % muted blue
    0.30 0.50 0.35   % muted green
    0.62 0.45 0.18   % muted ochre
    0.55 0.22 0.22   % muted red-brown
];

% Muted colours for stacked failure decomposition.
cfg.failureColors = [
    0.10 0.10 0.10   % dark grey / realised helping
    0.35 0.35 0.35   % grey
    0.23 0.37 0.55   % muted blue
    0.30 0.50 0.35   % muted green
    0.62 0.45 0.18   % muted ochre
    0.55 0.22 0.22   % muted red-brown
    0.45 0.32 0.55   % muted purple
];
end
