function cfg = sg_pubFigureConfig()
%SG_PUBFIGURECONFIG Figure defaults for the helping-behaviour manuscript.

cfg.taskOrder = string({ ...
    'instrumental_reaching', ...
    'visible_tool_transfer', ...
    'hidden_tool_transfer', ...
    'food_token_randomised', ...
    'food_token_fixed_position', ...
    'apparatus_bias_no_benefit', ...
    'low_competition_provisioning', ...
    'high_cost_help', ...
    'dominance_risk_help', ...
    'reliable_partner_collaboration'});

cfg.taskLabels = { ...
    'Instrumental', ...
    'Visible tool', ...
    'Hidden tool', ...
    'Food token rand.', ...
    'Food token fixed', ...
    'Bias/no benefit', ...
    'Provisioning', ...
    'High-cost', ...
    'Dominance-risk', ...
    'Collaboration'};

cfg.systemOrder = string({ ...
    'modOther_highComp', ...
    'highOther_modComp', ...
    'highOther_lowComp', ...
    'lowOther_weight', ...
    'pureSelf'});

cfg.systemLabels = { ...
    'Moderate other / high competition', ...
    'High other / moderate competition', ...
    'High other / low competition', ...
    'Low other-weight', ...
    'Pure self-interest'};

% Dark to light, restrained grayscale. One shade per parameter regime.
cfg.systemGrayMap = [ ...
    0.15 0.15 0.15; ...
    0.35 0.35 0.35; ...
    0.55 0.55 0.55; ...
    0.72 0.72 0.72; ...
    0.86 0.86 0.86];

cfg.failureVars = { ...
    'needFailureRate', ...
    'affordanceFailureRate', ...
    'costCompetitionOverrideRate', ...
    'valuationNoHelpRate', ...
    'falsePositiveBiasRate', ...
    'successRate'};

cfg.failureLabels = { ...
    'Need inference', ...
    'Affordance recognition', ...
    'Cost/competition override', ...
    'Valuation no-help', ...
    'False-positive bias', ...
    'Realised helping'};

% Dark to light for stacked classes. Keep realised helping light but visible.
cfg.failureGrayMap = [ ...
    0.18 0.18 0.18; ...
    0.32 0.32 0.32; ...
    0.46 0.46 0.46; ...
    0.60 0.60 0.60; ...
    0.74 0.74 0.74; ...
    0.86 0.86 0.86];

cfg.fontName = 'Arial';
cfg.fontSize = 8;
cfg.panelFontSize = 10;
cfg.axisLineWidth = 0.75;
cfg.groupedBarWidth = 0.70;
cfg.stackedBarWidth = 0.62;
cfg.exportResolution = 600;
end
